# ==========================================================
# ECDIP - Marketing Intelligence Generator
# ==========================================================

from pathlib import Path
import pandas as pd
import numpy as np

# ----------------------------------------------------------
# Configuration
# ----------------------------------------------------------

SEED = 42
np.random.seed(SEED)

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data" / "synthetic"

OUTPUT_FILE = DATA_DIR / "fact_marketing.csv"

# ----------------------------------------------------------
# Load existing enterprise data
# ----------------------------------------------------------

print("=" * 70)
print("ECDIP - MARKETING INTELLIGENCE GENERATOR")
print("=" * 70)

campaign = pd.read_csv(
    DATA_DIR / "dim_campaign.csv"
)

content = pd.read_csv(
    DATA_DIR / "dim_content.csv",
    usecols=[
        "content_id",
        "imdb_rating",
        "release_year"
    ]
)

region = pd.read_csv(
    DATA_DIR / "dim_region.csv",
    usecols=[
        "region_id"
    ]
)

viewing = pd.read_csv(
    DATA_DIR / "fact_viewing_events.csv",
    usecols=[
        "content_id",
        "region_id",
        "date_id",
        "watch_hours",
        "completion_rate",
        "marketing_influenced"
    ]
)

# ----------------------------------------------------------
# Validate source data
# ----------------------------------------------------------

required_campaign = [
    "campaign_id",
    "campaign_type",
    "campaign_channel",
    "start_date",
    "end_date",
    "budget"
]

for column in required_campaign:
    assert column in campaign.columns, (
        f"Missing campaign column: {column}"
    )

assert campaign["campaign_id"].is_unique
assert campaign["budget"].gt(0).all()

# ----------------------------------------------------------
# Create campaign performance records
# ----------------------------------------------------------

print("\nGenerating campaign performance...")

rows = []

for _, camp in campaign.iterrows():

    campaign_id = int(
        camp["campaign_id"]
    )

    budget = float(
        camp["budget"]
    )

    campaign_type = camp[
        "campaign_type"
    ]

    channel = camp[
        "campaign_channel"
    ]

    # ------------------------------------------------------
    # Campaign efficiency factors
    # ------------------------------------------------------

    channel_factor = {
        "YouTube": 1.15,
        "Instagram": 1.10,
        "Google": 1.08,
        "Television": 0.92,
        "Email": 1.20,
        "Influencer": 1.12,
        "In-App": 1.18,
        "Search": 1.05
    }.get(
        channel,
        1.0
    )

    campaign_factor = {
        "Content Launch": 1.20,
        "Seasonal": 1.15,
        "Retention": 1.10,
        "Acquisition": 1.05,
        "Brand Awareness": 0.90,
        "Regional Expansion": 1.12
    }.get(
        campaign_type,
        1.0
    )

    # ------------------------------------------------------
    # Generate marketing metrics
    # ------------------------------------------------------

    impressions = int(
        budget
        * np.random.uniform(
            15,
            40
        )
        * channel_factor
    )

    impressions = max(
        impressions,
        1000
    )

    click_rate = np.random.uniform(
        0.01,
        0.08
    )

    clicks = int(
        impressions
        * click_rate
    )

    conversion_rate = np.random.uniform(
        0.02,
        0.18
    )

    conversions = int(
        clicks
        * conversion_rate
        * campaign_factor
    )

    conversions = max(
        conversions,
        1
    )

    acquisition_cost = (
        budget / conversions
    )

    # ------------------------------------------------------
    # Marketing-influenced viewing
    # ------------------------------------------------------

    marketing_views = int(
        conversions
        * np.random.uniform(
            2,
            8
        )
    )

    attributed_watch_hours = (
        marketing_views
        * np.random.uniform(
            0.8,
            2.5
        )
    )

    # ------------------------------------------------------
    # Engagement generated by campaign
    # ------------------------------------------------------

    attributed_completion = np.clip(
        np.random.normal(
            65,
            12
        ),
        20,
        100
    )

    # ------------------------------------------------------
    # Estimated revenue impact
    # ------------------------------------------------------

    revenue_multiplier = np.random.uniform(
        1.5,
        4.0
    )

    attributed_revenue = (
        budget
        * revenue_multiplier
        * campaign_factor
        * channel_factor
    )

    attributed_revenue = max(
        attributed_revenue,
        0
    )

    # ------------------------------------------------------
    # ROI
    # ------------------------------------------------------

    marketing_roi = (
        attributed_revenue - budget
    ) / budget

    # ------------------------------------------------------
    # Record
    # ------------------------------------------------------

    rows.append({

        "campaign_id":
            campaign_id,

        "content_id":
            np.random.choice(
                content["content_id"]
            ),

        "region_id":
            np.random.choice(
                region["region_id"]
            ),

        "impressions":
            impressions,

        "clicks":
            clicks,

        "conversions":
            conversions,

        "marketing_views":
            marketing_views,

        "attributed_watch_hours":
            round(
                attributed_watch_hours,
                2
            ),

        "attributed_completion_rate":
            round(
                attributed_completion,
                2
            ),

        "marketing_spend":
            round(
                budget,
                2
            ),

        "attributed_revenue":
            round(
                attributed_revenue,
                2
            ),

        "acquisition_cost":
            round(
                acquisition_cost,
                2
            ),

        "marketing_roi":
            round(
                marketing_roi,
                4
            ),

        "created_at":
            pd.Timestamp.now()
    })


# ----------------------------------------------------------
# DataFrame
# ----------------------------------------------------------

marketing = pd.DataFrame(rows)

# ----------------------------------------------------------
# Enterprise validation
# ----------------------------------------------------------

print("\nRunning marketing data validation...")

assert not marketing.empty

assert marketing["campaign_id"].isin(
    campaign["campaign_id"]
).all()

assert marketing["content_id"].isin(
    content["content_id"]
).all()

assert marketing["region_id"].isin(
    region["region_id"]
).all()

assert marketing["impressions"].ge(0).all()

assert marketing["clicks"].ge(0).all()

assert marketing["conversions"].ge(0).all()

assert marketing["marketing_views"].ge(0).all()

assert marketing[
    "attributed_watch_hours"
].ge(0).all()

assert marketing[
    "attributed_completion_rate"
].between(
    0,
    100
).all()

assert marketing[
    "marketing_spend"
].gt(0).all()

assert marketing[
    "attributed_revenue"
].ge(0).all()

assert marketing[
    "acquisition_cost"
].gt(0).all()

assert not marketing[
    [
        "campaign_id",
        "content_id",
        "region_id"
    ]
].duplicated().any()

# ----------------------------------------------------------
# Create marketing ID
# ----------------------------------------------------------

marketing.insert(
    0,
    "marketing_id",
    np.arange(
        1,
        len(marketing) + 1
    )
)

assert marketing[
    "marketing_id"
].is_unique

# ----------------------------------------------------------
# Save
# ----------------------------------------------------------

marketing.to_csv(
    OUTPUT_FILE,
    index=False
)

# ----------------------------------------------------------
# Reporting
# ----------------------------------------------------------

print("\n" + "=" * 70)
print("MARKETING DATA GENERATED SUCCESSFULLY")
print("=" * 70)

print(
    f"Campaign records       : "
    f"{len(marketing):,}"
)

print(
    f"Total marketing spend  : "
    f"₹{marketing['marketing_spend'].sum():,.2f}"
)

print(
    f"Total attributed revenue: "
    f"₹{marketing['attributed_revenue'].sum():,.2f}"
)

print(
    f"Average conversion rate: "
    f"{(
        marketing['conversions'].sum()
        / marketing['clicks'].sum()
    ) * 100:.2f}%"
)

print(
    f"Average marketing ROI  : "
    f"{marketing['marketing_roi'].mean():.2f}"
)

print("\nValidation:")
print("✓ Campaign relationships valid")
print("✓ Content relationships valid")
print("✓ Region relationships valid")
print("✓ Impressions valid")
print("✓ Clicks valid")
print("✓ Conversions valid")
print("✓ Marketing spend valid")
print("✓ Revenue attribution valid")
print("✓ ROI calculated")
print("✓ Marketing IDs unique")

print("\nOutput:")
print(OUTPUT_FILE)

print("\nMARKETING INTELLIGENCE COMPLETE")