# ==============================================================================
# ECDIP - REAL MOVIES & TV SERIES MASTER CATALOG
# ==============================================================================
"""
Master curated catalog of iconic world cinema, blockbuster franchises,
and acclaimed streaming television series across Hollywood, Bollywood,
Asian cinema, and European cinema with authentic real-world metadata.
"""

REAL_STUDIOS = [
    {"studio_id": 1, "studio_name": "Warner Bros. Pictures", "headquarters_country": "United States", "founded_year": 1923, "website": "https://www.warnerbros.com"},
    {"studio_id": 2, "studio_name": "Universal Pictures", "headquarters_country": "United States", "founded_year": 1912, "website": "https://www.universalpictures.com"},
    {"studio_id": 3, "studio_name": "Walt Disney Pictures", "headquarters_country": "United States", "founded_year": 1923, "website": "https://movies.disney.com"},
    {"studio_id": 4, "studio_name": "Netflix Studios", "headquarters_country": "United States", "founded_year": 1997, "website": "https://www.netflix.com"},
    {"studio_id": 5, "studio_name": "Paramount Pictures", "headquarters_country": "United States", "founded_year": 1912, "website": "https://www.paramount.com"},
    {"studio_id": 6, "studio_name": "Sony Pictures Entertainment", "headquarters_country": "Japan", "founded_year": 1987, "website": "https://www.sonypictures.com"},
    {"studio_id": 7, "studio_name": "HBO Entertainment", "headquarters_country": "United States", "founded_year": 1972, "website": "https://www.hbo.com"},
    {"studio_id": 8, "studio_name": "A24", "headquarters_country": "United States", "founded_year": 2012, "website": "https://a24films.com"},
    {"studio_id": 9, "studio_name": "Marvel Studios", "headquarters_country": "United States", "founded_year": 1993, "website": "https://www.marvel.com"},
    {"studio_id": 10, "studio_name": "20th Century Studios", "headquarters_country": "United States", "founded_year": 1935, "website": "https://www.20thcenturystudios.com"},
    {"studio_id": 11, "studio_name": "Studio Ghibli", "headquarters_country": "Japan", "founded_year": 1985, "website": "https://www.ghibli.jp"},
    {"studio_id": 12, "studio_name": "Yash Raj Films", "headquarters_country": "India", "founded_year": 1970, "website": "https://www.yashrajfilms.com"},
    {"studio_id": 13, "studio_name": "Dharma Productions", "headquarters_country": "India", "founded_year": 1979, "website": "https://www.dharma-production.com"},
    {"studio_id": 14, "studio_name": "Toho Company", "headquarters_country": "Japan", "founded_year": 1932, "website": "https://www.toho.co.jp"},
    {"studio_id": 15, "studio_name": "Lionsgate Films", "headquarters_country": "Canada", "founded_year": 1997, "website": "https://www.lionsgate.com"},
    {"studio_id": 16, "studio_name": "MGM Studios", "headquarters_country": "United States", "founded_year": 1924, "website": "https://www.mgm.com"},
    {"studio_id": 17, "studio_name": "Legendary Entertainment", "headquarters_country": "United States", "founded_year": 2000, "website": "https://www.legendary.com"},
    {"studio_id": 18, "studio_name": "Lucasfilm", "headquarters_country": "United States", "founded_year": 1971, "website": "https://www.lucasfilm.com"},
    {"studio_id": 19, "studio_name": "DreamWorks Animation", "headquarters_country": "United States", "founded_year": 1994, "website": "https://www.dreamworks.com"},
    {"studio_id": 20, "studio_name": "Pixar Animation Studios", "headquarters_country": "United States", "founded_year": 1986, "website": "https://www.pixar.com"},
    {"studio_id": 21, "studio_name": "Columbia Pictures", "headquarters_country": "United States", "founded_year": 1924, "website": "https://www.sonypictures.com"},
    {"studio_id": 22, "studio_name": "Apple Studios", "headquarters_country": "United States", "founded_year": 2019, "website": "https://tv.apple.com"},
    {"studio_id": 23, "studio_name": "Amazon MGM Studios", "headquarters_country": "United States", "founded_year": 2010, "website": "https://www.mgm.com"},
    {"studio_id": 24, "studio_name": "Blumhouse Productions", "headquarters_country": "United States", "founded_year": 2000, "website": "https://www.blumhouse.com"},
    {"studio_id": 25, "studio_name": "CJ ENM Entertainment", "headquarters_country": "South Korea", "founded_year": 1995, "website": "https://www.cjenm.com"},
    {"studio_id": 26, "studio_name": "BBC Film", "headquarters_country": "United Kingdom", "founded_year": 1990, "website": "https://www.bbc.co.uk/film"},
    {"studio_id": 27, "studio_name": "Studio Dragon", "headquarters_country": "South Korea", "founded_year": 2016, "website": "http://www.studiodragon.net"},
    {"studio_id": 28, "studio_name": "Hombale Films", "headquarters_country": "India", "founded_year": 2012, "website": "https://www.hombale.com"},
    {"studio_id": 29, "studio_name": "DVV Entertainment", "headquarters_country": "India", "founded_year": 1993, "website": "https://dvventertainment.com"},
    {"studio_id": 30, "studio_name": "MAPPA Studio", "headquarters_country": "Japan", "founded_year": 2011, "website": "https://www.mappa.co.jp"}
]

REAL_TITLES = [
    # --- HOLLYWOOD BLOCKBUSTERS & SCI-FI MASTERPIECES ---
    {
        "title": "Inception",
        "content_type": "Movie",
        "genre": "Sci-Fi",
        "studio": "Warner Bros. Pictures",
        "release_year": 2010,
        "language": "English",
        "duration_minutes": 148,
        "age_rating": "PG-13",
        "imdb_rating": 8.8,
        "production_budget": 160000000,
        "is_original": False,
        "director": "Christopher Nolan",
        "cast": "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page, Tom Hardy",
        "synopsis": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
        "tags": ["Mind-Bending", "Oscar Winner", "IMDb Top 250"],
        "poster_url": "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#1e3a8a",
        "decision": "EXPAND"
    },
    {
        "title": "Interstellar",
        "content_type": "Movie",
        "genre": "Sci-Fi",
        "studio": "Paramount Pictures",
        "release_year": 2014,
        "language": "English",
        "duration_minutes": 169,
        "age_rating": "PG-13",
        "imdb_rating": 8.7,
        "production_budget": 165000000,
        "is_original": False,
        "director": "Christopher Nolan",
        "cast": "Matthew McConaughey, Anne Hathaway, Jessica Chastain, Michael Caine",
        "synopsis": "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
        "tags": ["Space Exploration", "Deep Emotion", "Hans Zimmer Score"],
        "poster_url": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#0f172a",
        "decision": "EXPAND"
    },
    {
        "title": "Oppenheimer",
        "content_type": "Movie",
        "genre": "Biography",
        "studio": "Universal Pictures",
        "release_year": 2023,
        "language": "English",
        "duration_minutes": 180,
        "age_rating": "R",
        "imdb_rating": 8.9,
        "production_budget": 100000000,
        "is_original": False,
        "director": "Christopher Nolan",
        "cast": "Cillian Murphy, Emily Blunt, Matt Damon, Robert Downey Jr.",
        "synopsis": "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during the Manhattan Project.",
        "tags": ["7 Oscars Winner", "Historical Epic", "Blockbuster Drama"],
        "poster_url": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#ea580c",
        "decision": "EXPAND"
    },
    {
        "title": "The Dark Knight",
        "content_type": "Movie",
        "genre": "Action",
        "studio": "Warner Bros. Pictures",
        "release_year": 2008,
        "language": "English",
        "duration_minutes": 152,
        "age_rating": "PG-13",
        "imdb_rating": 9.0,
        "production_budget": 185000000,
        "is_original": False,
        "director": "Christopher Nolan",
        "cast": "Christian Bale, Heath Ledger, Aaron Eckhart, Michael Caine",
        "synopsis": "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        "tags": ["Heath Ledger Joker", "Masterpiece", "Highest Rated Superhero Film"],
        "poster_url": "https://images.unsplash.com/photo-1509281373149-e957c6296406?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#334155",
        "decision": "EXPAND"
    },
    {
        "title": "Dune: Part Two",
        "content_type": "Movie",
        "genre": "Sci-Fi",
        "studio": "Warner Bros. Pictures",
        "release_year": 2024,
        "language": "English",
        "duration_minutes": 166,
        "age_rating": "PG-13",
        "imdb_rating": 8.6,
        "production_budget": 190000000,
        "is_original": False,
        "director": "Denis Villeneuve",
        "cast": "Timothée Chalamet, Zendaya, Rebecca Ferguson, Javier Bardem",
        "synopsis": "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the universe.",
        "tags": ["Sci-Fi Epic", "Visual Marvel", "Global Phenomenon"],
        "poster_url": "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#d97706",
        "decision": "EXPAND"
    },
    {
        "title": "Avengers: Endgame",
        "content_type": "Movie",
        "genre": "Action",
        "studio": "Marvel Studios",
        "release_year": 2019,
        "language": "English",
        "duration_minutes": 181,
        "age_rating": "PG-13",
        "imdb_rating": 8.4,
        "production_budget": 356000000,
        "is_original": False,
        "director": "Anthony Russo, Joe Russo",
        "cast": "Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson",
        "synopsis": "After the devastating events of Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions.",
        "tags": ["$2.8B Box Office", "MCU Climax", "Fan Favorite"],
        "poster_url": "https://images.unsplash.com/photo-1635863138275-d9b33299680b?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#4c1d95",
        "decision": "EXPAND"
    },
    {
        "title": "Spider-Man: Across the Spider-Verse",
        "content_type": "Movie",
        "genre": "Animation",
        "studio": "Sony Pictures Entertainment",
        "release_year": 2023,
        "language": "English",
        "duration_minutes": 140,
        "age_rating": "PG",
        "imdb_rating": 8.7,
        "production_budget": 100000000,
        "is_original": False,
        "director": "Joaquim Dos Santos, Kemp Powers, Justin K. Thompson",
        "cast": "Shameik Moore, Hailee Steinfeld, Oscar Isaac, Daniel Kaluuya",
        "synopsis": "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.",
        "tags": ["Groundbreaking Animation", "Multiverse", "Universal Acclaim"],
        "poster_url": "https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#dc2626",
        "decision": "EXPAND"
    },
    {
        "title": "Pulp Fiction",
        "content_type": "Movie",
        "genre": "Crime",
        "studio": "Universal Pictures",
        "release_year": 1994,
        "language": "English",
        "duration_minutes": 154,
        "age_rating": "R",
        "imdb_rating": 8.9,
        "production_budget": 8500000,
        "is_original": False,
        "director": "Quentin Tarantino",
        "cast": "John Travolta, Uma Thurman, Samuel L. Jackson, Bruce Willis",
        "synopsis": "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        "tags": ["Cult Classic", "Palme d'Or", "Legendary Dialogue"],
        "poster_url": "https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#b91c1c",
        "decision": "EXPAND"
    },
    {
        "title": "The Matrix",
        "content_type": "Movie",
        "genre": "Sci-Fi",
        "studio": "Warner Bros. Pictures",
        "release_year": 1999,
        "language": "English",
        "duration_minutes": 136,
        "age_rating": "R",
        "imdb_rating": 8.7,
        "production_budget": 63000000,
        "is_original": False,
        "director": "Lana Wachowski, Lilly Wachowski",
        "cast": "Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving",
        "synopsis": "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
        "tags": ["Sci-Fi Milestone", "Bullet Time", "Evergreen Hit"],
        "poster_url": "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#15803d",
        "decision": "EXPAND"
    },
    {
        "title": "Everything Everywhere All at Once",
        "content_type": "Movie",
        "genre": "Sci-Fi",
        "studio": "A24",
        "release_year": 2022,
        "language": "English",
        "duration_minutes": 139,
        "age_rating": "R",
        "imdb_rating": 7.8,
        "production_budget": 25000000,
        "is_original": False,
        "director": "Daniel Kwan, Daniel Scheinert",
        "cast": "Michelle Yeoh, Stephanie Hsu, Ke Huy Quan, Jamie Lee Curtis",
        "synopsis": "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes and connecting with the lives she could have led.",
        "tags": ["Best Picture Winner", "Multiverse", "A24 Breakthrough"],
        "poster_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#7c3aed",
        "decision": "EXPAND"
    },
    {
        "title": "Top Gun: Maverick",
        "content_type": "Movie",
        "genre": "Action",
        "studio": "Paramount Pictures",
        "release_year": 2022,
        "language": "English",
        "duration_minutes": 130,
        "age_rating": "PG-13",
        "imdb_rating": 8.3,
        "production_budget": 170000000,
        "is_original": False,
        "director": "Joseph Kosinski",
        "cast": "Tom Cruise, Miles Teller, Jennifer Connelly, Jon Hamm",
        "synopsis": "After thirty years, Maverick is still pushing the envelope as a top naval aviator, but must confront ghosts of his past when he leads TOP GUN's elite graduates on an impossible mission.",
        "tags": ["Aerial Spectacle", "Global Blockbuster", "High Adrenaline"],
        "poster_url": "https://images.unsplash.com/photo-1519074069444-1ba4ea16e897?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#0369a1",
        "decision": "EXPAND"
    },
    {
        "title": "Gladiator II",
        "content_type": "Movie",
        "genre": "Action",
        "studio": "Paramount Pictures",
        "release_year": 2024,
        "language": "English",
        "duration_minutes": 148,
        "age_rating": "R",
        "imdb_rating": 7.3,
        "production_budget": 210000000,
        "is_original": False,
        "director": "Ridley Scott",
        "cast": "Paul Mescal, Pedro Pascal, Denzel Washington, Connie Nielsen",
        "synopsis": "Years after witnessing the death of Maximus at the hands of his uncle, Lucius must enter the Colosseum after the powerful emperors of Rome conquer his home.",
        "tags": ["Historical Epic", "Colosseum", "Franchise Revival"],
        "poster_url": "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#78350f",
        "decision": "MONITOR"
    },
    {
        "title": "Avatar: The Way of Water",
        "content_type": "Movie",
        "genre": "Sci-Fi",
        "studio": "20th Century Studios",
        "release_year": 2022,
        "language": "English",
        "duration_minutes": 192,
        "age_rating": "PG-13",
        "imdb_rating": 7.6,
        "production_budget": 350000000,
        "is_original": False,
        "director": "James Cameron",
        "cast": "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang",
        "synopsis": "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race.",
        "tags": ["$2.3B Gross", "Underwater 3D", "Cinematic Benchmark"],
        "poster_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#0284c7",
        "decision": "EXPAND"
    },
    {
        "title": "Parasite",
        "content_type": "Movie",
        "genre": "Drama",
        "studio": "CJ ENM Entertainment",
        "release_year": 2019,
        "language": "Korean",
        "duration_minutes": 132,
        "age_rating": "R",
        "imdb_rating": 8.5,
        "production_budget": 15500000,
        "is_original": False,
        "director": "Bong Joon-ho",
        "cast": "Song Kang-ho, Lee Sun-kyun, Cho Yeo-jeong, Choi Woo-shik",
        "synopsis": "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
        "tags": ["First Foreign Best Picture", "Masterpiece", "Social Thriller"],
        "poster_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#14532d",
        "decision": "EXPAND"
    },
    {
        "title": "Spirited Away",
        "content_type": "Movie",
        "genre": "Animation",
        "studio": "Studio Ghibli",
        "release_year": 2001,
        "language": "Japanese",
        "duration_minutes": 125,
        "age_rating": "PG",
        "imdb_rating": 8.6,
        "production_budget": 19200000,
        "is_original": False,
        "director": "Hayao Miyazaki",
        "cast": "Rumi Hiiragi, Miyu Irino, Mari Natsuki, Takashi Naito",
        "synopsis": "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches and spirits, a world where humans are changed into beasts.",
        "tags": ["Ghibli Crown Jewel", "Oscar Winner", "Universal Evergreen"],
        "poster_url": "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#047857",
        "decision": "EXPAND"
    },
    {
        "title": "Your Name",
        "content_type": "Movie",
        "genre": "Animation",
        "studio": "Toho Company",
        "release_year": 2016,
        "language": "Japanese",
        "duration_minutes": 106,
        "age_rating": "PG",
        "imdb_rating": 8.4,
        "production_budget": 5000000,
        "is_original": False,
        "director": "Makoto Shinkai",
        "cast": "Ryunosuke Kamiki, Mone Kamishiraishi, Ryo Narita",
        "synopsis": "Two teenagers share a profound, magical connection upon discovering they are swapping bodies. Things manage to become even more complicated when the boy and girl decide to meet in person.",
        "tags": ["Anime Masterpiece", "Sensational OST", "Emotional Resonance"],
        "poster_url": "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#4338ca",
        "decision": "EXPAND"
    },

    # --- INDIAN / BOLLYWOOD & PAN-INDIA MEGA-HITS ---
    {
        "title": "RRR",
        "content_type": "Movie",
        "genre": "Action",
        "studio": "DVV Entertainment",
        "release_year": 2022,
        "language": "Hindi",
        "duration_minutes": 187,
        "age_rating": "PG-13",
        "imdb_rating": 7.8,
        "production_budget": 68000000,
        "is_original": False,
        "director": "S.S. Rajamouli",
        "cast": "N.T. Rama Rao Jr., Ram Charan, Ajay Devgn, Alia Bhatt",
        "synopsis": "A fearless revolutionary and an officer in the British force, who once shared a deep bond, decide to join forces and chart out an inspirational path of freedom against the despotic rulers.",
        "tags": ["Naatu Naatu Oscar", "Global Sensation", "Visual Action Spectacle"],
        "poster_url": "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#b45309",
        "decision": "EXPAND"
    },
    {
        "title": "K.G.F: Chapter 2",
        "content_type": "Movie",
        "genre": "Action",
        "studio": "Hombale Films",
        "release_year": 2022,
        "language": "Hindi",
        "duration_minutes": 168,
        "age_rating": "PG-13",
        "imdb_rating": 8.2,
        "production_budget": 13000000,
        "is_original": False,
        "director": "Prashanth Neel",
        "cast": "Yash, Sanjay Dutt, Raveena Tandon, Srinidhi Shetty",
        "synopsis": "The blood-soaked land of Kolar Gold Fields has a new overlord now - Rocky, whose name strikes fear in the heart of his foes. His allies look up to him as their savior.",
        "tags": ["Pan-India Record Breaker", "Monster Action", "Cult Hero"],
        "poster_url": "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#78350f",
        "decision": "EXPAND"
    },
    {
        "title": "Baahubali 2: The Conclusion",
        "content_type": "Movie",
        "genre": "Fantasy",
        "studio": "DVV Entertainment",
        "release_year": 2017,
        "language": "Hindi",
        "duration_minutes": 167,
        "age_rating": "PG-13",
        "imdb_rating": 8.2,
        "production_budget": 37000000,
        "is_original": False,
        "director": "S.S. Rajamouli",
        "cast": "Prabhas, Rana Daggubati, Anushka Shetty, Tamannaah Bhatia",
        "synopsis": "When Shiva, the son of Bahubali, learns about his heritage, he begins to look for answers. His story is juxtaposed with past events that unfolded in the Mahishmati Kingdom.",
        "tags": ["Historic All-Time Grosser", "Epic Folklore", "Iconic Climax"],
        "poster_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#991b1b",
        "decision": "EXPAND"
    },
    {
        "title": "Dangal",
        "content_type": "Movie",
        "genre": "Biography",
        "studio": "Universal Pictures",
        "release_year": 2016,
        "language": "Hindi",
        "duration_minutes": 161,
        "age_rating": "PG",
        "imdb_rating": 8.3,
        "production_budget": 10000000,
        "is_original": False,
        "director": "Nitesh Tiwari",
        "cast": "Aamir Khan, Sakshi Tanwar, Fatima Sana Shaikh, Sanya Malhotra",
        "synopsis": "Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games in the face of societal oppression.",
        "tags": ["Global Box Office Giant", "Highest Grossing Indian Film", "Inspiring Sports"],
        "poster_url": "https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#b45309",
        "decision": "EXPAND"
    },
    {
        "title": "3 Idiots",
        "content_type": "Movie",
        "genre": "Comedy",
        "studio": "Universal Pictures",
        "release_year": 2009,
        "language": "Hindi",
        "duration_minutes": 170,
        "age_rating": "PG-13",
        "imdb_rating": 8.4,
        "production_budget": 8000000,
        "is_original": False,
        "director": "Rajkumar Hirani",
        "cast": "Aamir Khan, Madhavan, Sharman Joshi, Kareena Kapoor",
        "synopsis": "Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently.",
        "tags": ["Timeless Classic", "Global Cultural Phenomenon", "All-Time Favorite"],
        "poster_url": "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#0284c7",
        "decision": "EXPAND"
    },
    {
        "title": "Tumbbad",
        "content_type": "Movie",
        "genre": "Fantasy",
        "studio": "Universal Pictures",
        "release_year": 2018,
        "language": "Hindi",
        "duration_minutes": 104,
        "age_rating": "TV-MA",
        "imdb_rating": 8.2,
        "production_budget": 2000000,
        "is_original": False,
        "director": "Rahi Anil Barve, Anand Gandhi",
        "cast": "Sohum Shah, Jyoti Malshe, Anita Date, Ronjini Chakraborty",
        "synopsis": "A mythological story about a goddess who created the entire universe. The plot revolves around the consequences when humans build a temple for her first-born demon son, Hastar.",
        "tags": ["Folk Horror Masterpiece", "Atmospheric Genius", "Huge Cult Following"],
        "poster_url": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#451a03",
        "decision": "EXPAND"
    },
    {
        "title": "Jawan",
        "content_type": "Movie",
        "genre": "Action",
        "studio": "Universal Pictures",
        "release_year": 2023,
        "language": "Hindi",
        "duration_minutes": 169,
        "age_rating": "PG-13",
        "imdb_rating": 7.0,
        "production_budget": 38000000,
        "is_original": False,
        "director": "Atlee",
        "cast": "Shah Rukh Khan, Nayanthara, Vijay Sethupathi, Deepika Padukone",
        "synopsis": "A high-octane action thriller which outlines the emotional journey of a man who is set to rectify the wrongs in the society, driven by a personal vendetta while keeping a promise made years ago.",
        "tags": ["Shah Rukh Khan Record", "Mass Entertainer", "Box Office Monster"],
        "poster_url": "https://images.unsplash.com/photo-1509281373149-e957c6296406?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#991b1b",
        "decision": "EXPAND"
    },
    {
        "title": "Andhadhun",
        "content_type": "Movie",
        "genre": "Thriller",
        "studio": "Universal Pictures",
        "release_year": 2018,
        "language": "Hindi",
        "duration_minutes": 139,
        "age_rating": "TV-MA",
        "imdb_rating": 8.2,
        "production_budget": 4500000,
        "is_original": False,
        "director": "Sriram Raghavan",
        "cast": "Ayushmann Khurrana, Tabu, Radhika Apte, Anil Dhawan",
        "synopsis": "A series of mysterious events change the life of a blind pianist, who now must report a crime that he should technically know nothing of.",
        "tags": ["Dark Comedy Thriller", "Unpredictable Twists", "Critical Darling"],
        "poster_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#1e293b",
        "decision": "EXPAND"
    },

    # --- PRESTIGE TV SERIES & STREAMING PHENOMENA ---
    {
        "title": "Stranger Things",
        "content_type": "Series",
        "genre": "Sci-Fi",
        "studio": "Netflix Studios",
        "release_year": 2016,
        "language": "English",
        "duration_minutes": 55,
        "age_rating": "TV-14",
        "imdb_rating": 8.7,
        "production_budget": 270000000,
        "is_original": True,
        "director": "The Duffer Brothers",
        "cast": "Millie Bobby Brown, Finn Wolfhard, Winona Ryder, David Harbour",
        "synopsis": "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
        "tags": ["Flagship Original", "80s Nostalgia", "Global Phenomenon"],
        "poster_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#991b1b",
        "decision": "RENEW"
    },
    {
        "title": "Succession",
        "content_type": "Series",
        "genre": "Drama",
        "studio": "HBO Entertainment",
        "release_year": 2018,
        "language": "English",
        "duration_minutes": 60,
        "age_rating": "TV-MA",
        "imdb_rating": 8.9,
        "production_budget": 90000000,
        "is_original": True,
        "director": "Jesse Armstrong",
        "cast": "Brian Cox, Jeremy Strong, Sarah Snook, Kieran Culkin, Matthew Macfadyen",
        "synopsis": "The Roy family is known for controlling the biggest media and entertainment company in the world. However, their world changes when their aging father steps down from the company.",
        "tags": ["Multiple Emmy Winner", "Corporate Warfare", "Masterpiece Writing"],
        "poster_url": "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#1e293b",
        "decision": "EXPAND"
    },
    {
        "title": "The Bear",
        "content_type": "Series",
        "genre": "Drama",
        "studio": "Universal Pictures",
        "release_year": 2022,
        "language": "English",
        "duration_minutes": 35,
        "age_rating": "TV-MA",
        "imdb_rating": 8.6,
        "production_budget": 35000000,
        "is_original": False,
        "director": "Christopher Storer",
        "cast": "Jeremy Allen White, Ebon Moss-Bachrach, Ayo Edebiri, Lionel Boyce",
        "synopsis": "A young chef from the fine dining world returns to Chicago to run his family's Italian beef sandwich shop after a heartbreaking death in his family.",
        "tags": ["High Voltage", "Emmy Sweeper", "Culinary Drama"],
        "poster_url": "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#0284c7",
        "decision": "EXPAND"
    },
    {
        "title": "Severance",
        "content_type": "Series",
        "genre": "Sci-Fi",
        "studio": "Apple Studios",
        "release_year": 2022,
        "language": "English",
        "duration_minutes": 55,
        "age_rating": "TV-MA",
        "imdb_rating": 8.7,
        "production_budget": 45000000,
        "is_original": False,
        "director": "Ben Stiller, Aoife McArdle",
        "cast": "Adam Scott, Zach Cherry, Britt Lower, Patricia Arquette, John Turturro",
        "synopsis": "Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives. When a mysterious colleague appears outside of work, it begins a journey to discover the truth about their jobs.",
        "tags": ["Dystopian Mystery", "Mind-Bending", "Critical Acclaim"],
        "poster_url": "https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#0f766e",
        "decision": "EXPAND"
    },
    {
        "title": "Squid Game",
        "content_type": "Series",
        "genre": "Thriller",
        "studio": "Netflix Studios",
        "release_year": 2021,
        "language": "Korean",
        "duration_minutes": 55,
        "age_rating": "TV-MA",
        "imdb_rating": 8.0,
        "production_budget": 21400000,
        "is_original": True,
        "director": "Hwang Dong-hyuk",
        "cast": "Lee Jung-jae, Park Hae-soo, Wi Ha-joon, Jung Ho-yeon",
        "synopsis": "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits with deadly high stakes.",
        "tags": ["Most Watched Series Ever", "Global Viral Sensation", "Cultural Benchmark"],
        "poster_url": "https://images.unsplash.com/photo-1634838080334-28befa9efe80?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#be123c",
        "decision": "EXPAND"
    },
    {
        "title": "Breaking Bad",
        "content_type": "Series",
        "genre": "Crime",
        "studio": "Sony Pictures Entertainment",
        "release_year": 2008,
        "language": "English",
        "duration_minutes": 49,
        "age_rating": "TV-MA",
        "imdb_rating": 9.5,
        "production_budget": 65000000,
        "is_original": False,
        "director": "Vince Gilligan",
        "cast": "Bryan Cranston, Aaron Paul, Anna Gunn, Dean Norris, Giancarlo Esposito",
        "synopsis": "A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student in order to secure his family's future.",
        "tags": ["Greatest Series of All Time", "Peak TV", "Unrivaled Binge"],
        "poster_url": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#15803d",
        "decision": "EXPAND"
    },
    {
        "title": "The Last of Us",
        "content_type": "Series",
        "genre": "Drama",
        "studio": "HBO Entertainment",
        "release_year": 2023,
        "language": "English",
        "duration_minutes": 60,
        "age_rating": "TV-MA",
        "imdb_rating": 8.8,
        "production_budget": 100000000,
        "is_original": False,
        "director": "Craig Mazin, Neil Druckmann",
        "cast": "Pedro Pascal, Bella Ramsey, Gabriel Luna, Anna Torv",
        "synopsis": "After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity's last hope.",
        "tags": ["Post-Apocalyptic Masterpiece", "Gaming Adaptation Benchmark", "Emotional Powerhouse"],
        "poster_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#3f6212",
        "decision": "EXPAND"
    },
    {
        "title": "Chernobyl",
        "content_type": "Series",
        "genre": "Drama",
        "studio": "HBO Entertainment",
        "release_year": 2019,
        "language": "English",
        "duration_minutes": 65,
        "age_rating": "TV-MA",
        "imdb_rating": 9.4,
        "production_budget": 40000000,
        "is_original": False,
        "director": "Johan Renck, Craig Mazin",
        "cast": "Jared Harris, Stellan Skarsgård, Emily Watson, Paul Ritter",
        "synopsis": "In April 1986, an explosion at the Chernobyl nuclear power plant in the Soviet Union becomes one of the world's worst man-made catastrophes.",
        "tags": ["Flawless Miniseries", "Historical Drama", "Gripping Realism"],
        "poster_url": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#854d0e",
        "decision": "EXPAND"
    },
    {
        "title": "Arcane",
        "content_type": "Series",
        "genre": "Animation",
        "studio": "Netflix Studios",
        "release_year": 2021,
        "language": "English",
        "duration_minutes": 42,
        "age_rating": "TV-14",
        "imdb_rating": 9.0,
        "production_budget": 80000000,
        "is_original": True,
        "director": "Christian Linke, Alex Yee",
        "cast": "Hailee Steinfeld, Ella Purnell, Kevin Alejandro, Katie Leung",
        "synopsis": "Set in the utopian region of Piltover and the oppressed underground of Zaun, the story follows the origins of two iconic League champions-and the power that will tear them apart.",
        "tags": ["Visual Art Landmark", "Emmy Winner", "Unanimous Praise"],
        "poster_url": "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#701a75",
        "decision": "RENEW"
    },
    {
        "title": "Attack on Titan",
        "content_type": "Series",
        "genre": "Animation",
        "studio": "MAPPA Studio",
        "release_year": 2013,
        "language": "Japanese",
        "duration_minutes": 24,
        "age_rating": "TV-MA",
        "imdb_rating": 9.1,
        "production_budget": 35000000,
        "is_original": False,
        "director": "Tetsuro Araki, Yuichiro Hayashi",
        "cast": "Yuki Kaji, Yui Ishikawa, Marina Inoue, Hiroshi Kamiya",
        "synopsis": "After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.",
        "tags": ["Global Anime Colossus", "Storytelling Marvel", "Mind-Blowing Twists"],
        "poster_url": "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#7f1d1d",
        "decision": "EXPAND"
    },
    {
        "title": "Shōgun",
        "content_type": "Series",
        "genre": "Drama",
        "studio": "Universal Pictures",
        "release_year": 2024,
        "language": "Japanese",
        "duration_minutes": 60,
        "age_rating": "TV-MA",
        "imdb_rating": 8.7,
        "production_budget": 120000000,
        "is_original": False,
        "director": "Rachel Kondo, Justin Marks",
        "cast": "Hiroyuki Sanada, Cosmo Jarvis, Anna Sawai, Tadanobu Asano",
        "synopsis": "When a mysterious European ship is found marooned in a nearby fishing village, Lord Yoshii Toranaga discovers secrets that could tip the scales of power and devastate his formidable enemies.",
        "tags": ["18 Emmy Record", "Samurai Epic", "Masterclass In Television"],
        "poster_url": "https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#831843",
        "decision": "EXPAND"
    },
    {
        "title": "The Boys",
        "content_type": "Series",
        "genre": "Action",
        "studio": "Amazon MGM Studios",
        "release_year": 2019,
        "language": "English",
        "duration_minutes": 60,
        "age_rating": "TV-MA",
        "imdb_rating": 8.7,
        "production_budget": 95000000,
        "is_original": False,
        "director": "Eric Kripke",
        "cast": "Karl Urban, Jack Quaid, Antony Starr, Erin Moriarty",
        "synopsis": "A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers instead of using them for good.",
        "tags": ["Subversive Satire", "Viral Homelander", "Uncensored Thrills"],
        "poster_url": "https://images.unsplash.com/photo-1509281373149-e957c6296406?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#1e3a8a",
        "decision": "EXPAND"
    },
    {
        "title": "Ted Lasso",
        "content_type": "Series",
        "genre": "Comedy",
        "studio": "Apple Studios",
        "release_year": 2020,
        "language": "English",
        "duration_minutes": 40,
        "age_rating": "TV-MA",
        "imdb_rating": 8.8,
        "production_budget": 60000000,
        "is_original": False,
        "director": "Brendan Hunt, Joe Kelly, Bill Lawrence",
        "cast": "Jason Sudeikis, Hannah Waddingham, Jeremy Swift, Phil Dunster, Brett Goldstein",
        "synopsis": "American college football coach Ted Lasso heads to London to manage AFC Richmond, a struggling English Premier League football team.",
        "tags": ["Heartwarming Comedy", "Emmy Darling", "Feel-Good Titan"],
        "poster_url": "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#eab308",
        "decision": "EXPAND"
    },
    {
        "title": "Dark",
        "content_type": "Series",
        "genre": "Sci-Fi",
        "studio": "Netflix Studios",
        "release_year": 2017,
        "language": "German",
        "duration_minutes": 53,
        "age_rating": "TV-MA",
        "imdb_rating": 8.7,
        "production_budget": 30000000,
        "is_original": True,
        "director": "Baran bo Odar, Jantje Friese",
        "cast": "Louis Hofmann, Oliver Masucci, Jördis Triebel, Maja Schöne",
        "synopsis": "A family saga with a supernatural twist, set in a German town where the disappearance of two young children exposes the relationships among four families and a time-travel conspiracy.",
        "tags": ["Intricate Time Travel", "German Sci-Fi Benchmark", "Cult Classic"],
        "poster_url": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#334155",
        "decision": "EXPAND"
    },
    {
        "title": "Money Heist",
        "content_type": "Series",
        "genre": "Crime",
        "studio": "Netflix Studios",
        "release_year": 2017,
        "language": "Spanish",
        "duration_minutes": 50,
        "age_rating": "TV-MA",
        "imdb_rating": 8.2,
        "production_budget": 45000000,
        "is_original": True,
        "director": "Álex Pina",
        "cast": "Úrsula Corberó, Álvaro Morte, Itziar Ituño, Pedro Alonso",
        "synopsis": "An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.",
        "tags": ["Global Binge Titan", "Bella Ciao", "Spanish Sensation"],
        "poster_url": "https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#991b1b",
        "decision": "EXPAND"
    },
    {
        "title": "Black Mirror",
        "content_type": "Series",
        "genre": "Sci-Fi",
        "studio": "Netflix Studios",
        "release_year": 2011,
        "language": "English",
        "duration_minutes": 60,
        "age_rating": "TV-MA",
        "imdb_rating": 8.7,
        "production_budget": 50000000,
        "is_original": True,
        "director": "Charlie Brooker",
        "cast": "Daniel Lapaine, Hannah John-Kamen, Michaela Coel, Bryce Dallas Howard",
        "synopsis": "An anthology series exploring a twisted, high-tech multiverse where humanity's greatest innovations and darkest instincts collide.",
        "tags": ["Tech Satire", "Mind-Altering", "Anthology Standard"],
        "poster_url": "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#18181b",
        "decision": "EXPAND"
    },
    {
        "title": "The Mandalorian",
        "content_type": "Series",
        "genre": "Action",
        "studio": "Lucasfilm",
        "release_year": 2019,
        "language": "English",
        "duration_minutes": 40,
        "age_rating": "TV-14",
        "imdb_rating": 8.6,
        "production_budget": 120000000,
        "is_original": False,
        "director": "Jon Favreau, Dave Filoni",
        "cast": "Pedro Pascal, Carl Weathers, Giancarlo Esposito, Katee Sackhoff",
        "synopsis": "The travels of a lone bounty hunter in the outer reaches of the galaxy, far from the authority of the New Republic, protecting an extraordinary child.",
        "tags": ["Star Wars Hit", "Baby Yoda", "High Production Values"],
        "poster_url": "https://images.unsplash.com/photo-1509281373149-e957c6296406?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#0369a1",
        "decision": "EXPAND"
    },
    {
        "title": "The Crown",
        "content_type": "Series",
        "genre": "Drama",
        "studio": "Netflix Studios",
        "release_year": 2016,
        "language": "English",
        "duration_minutes": 58,
        "age_rating": "TV-MA",
        "imdb_rating": 8.6,
        "production_budget": 130000000,
        "is_original": True,
        "director": "Peter Morgan",
        "cast": "Claire Foy, Olivia Colman, Imelda Staunton, Matt Smith",
        "synopsis": "Follows the political rivalries and romance of Queen Elizabeth II's reign and the events that shaped the second half of the twentieth century.",
        "tags": ["Lavish Production", "Royal Drama", "Multi-Emmy Winner"],
        "poster_url": "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#ca8a04",
        "decision": "MONITOR"
    },
    {
        "title": "Peaky Blinders",
        "content_type": "Series",
        "genre": "Crime",
        "studio": "BBC Film",
        "release_year": 2013,
        "language": "English",
        "duration_minutes": 58,
        "age_rating": "TV-MA",
        "imdb_rating": 8.8,
        "production_budget": 45000000,
        "is_original": False,
        "director": "Steven Knight",
        "cast": "Cillian Murphy, Paul Anderson, Sophie Rundle, Helen McCrory, Tom Hardy",
        "synopsis": "A gangster family epic set in 1900s England, centering on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby.",
        "tags": ["Tommy Shelby", "Stylish Crime", "Atmospheric Masterpiece"],
        "poster_url": "https://images.unsplash.com/photo-1594909122845-11baa439b7bf?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#1c1917",
        "decision": "EXPAND"
    },
    {
        "title": "House of the Dragon",
        "content_type": "Series",
        "genre": "Fantasy",
        "studio": "HBO Entertainment",
        "release_year": 2022,
        "language": "English",
        "duration_minutes": 60,
        "age_rating": "TV-MA",
        "imdb_rating": 8.4,
        "production_budget": 200000000,
        "is_original": False,
        "director": "Ryan J. Condal, George R.R. Martin",
        "cast": "Matt Smith, Emma D'Arcy, Olivia Cooke, Paddy Considine",
        "synopsis": "An internal succession war within House Targaryen at the height of its power, 172 years before the birth of Daenerys Targaryen.",
        "tags": ["Targaryen Civil War", "Dragons", "Global Ratings Giant"],
        "poster_url": "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80",
        "poster_color": "#7f1d1d",
        "decision": "EXPAND"
    }
]

REALISTIC_PREFIXES = [
    "The Last", "Shadow of", "Echoes of", "Chronicles of", "The Secret", "Return of",
    "Beyond the", "Rise of", "Song of", "Heart of", "Kingdom of", "Legacy of",
    "City of", "Whispers in", "Trial of", "Age of", "Flight of", "Ghosts of",
    "Call of", "Borders of", "Edge of", "Children of", "Empire of", "Prophecy of",
    "Code", "Operation", "Project", "Under", "Inside", "Before", "After"
]

REALISTIC_CORES = [
    "Olympus", "Eternity", "Tomorrow", "Destiny", "Honor", "Silence", "Midnight",
    "Freedom", "Justice", "Redemption", "Horizon", "Paradise", "Darkness", "Light",
    "Storm", "Thunder", "Valor", "Nemesis", "Illusion", "Vengeance", "Reckoning",
    "Avalon", "Syndicate", "Protocol", "Monolith", "Sanctuary", "Eclipse", "Labyrinth",
    "Ascendance", "Paradox", "Frontier", "Dynasty", "Requiem", "Odyssey", "Genesis"
]

REALISTIC_SUFFIXES = [
    "Reborn", "Unbound", "Chronicles", "Rising", "Awakening", "Origins", "Protocol",
    "Legacy", "Fallout", "Resurgence", "Vindication", "Retribution", "Extraction",
    "Ascension", "Conspiracy", "Evolution", "Defiance", "Endgame", "Revelation"
]
